#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Set the dotfiles dir 
export DOTDIR=$HOME/.dotfiles

# Use .config for as much things as possible
export XDG_CONFIG_HOME=$HOME/.config

export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s $ZDOTDIR:-$HOME/.zprofile ]]; then
  source $ZDOTDIR:-$HOME/.zprofile
fi

# Applications alias
# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Needed for neovim-remote to work
# export PYTHON_HOME=$HOME/Library/Python/3.6/bin
# export PATH=$PATH:$PYTHON_HOME
# export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
# export PATH="/usr/local/opt/gettext/bin:$PATH"


# Shortcuts for neovim Dirs
export VIMCONFIG=$XDG_CONFIG_HOME/nvim
export VIMDATA=$HOME/.local/share/nvim

# Use .config for as much things as possible
export GIT_CONFIG=$XDG_CONFIG_HOME/git/config

# Put executables from .dotfiles in PATH
export PATH=$PATH:$DOTDIR/bin

# Source aliases
source $DOTDIR/aliases
