#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Run nvm
# export NVM_DIR=~/.nvm
# source $(brew --prefix nvm)/nvm.sh

# Alias for running local npm modules
# alias npm-local='PATH=$(npm bin):$PATH'

export TERM=xterm-256color-italic

# Resmio alias
alias vagrantdock='vagrant up --provider=docker --no-parallel'
alias telegram='/Users/menor/code/tg/bin/telegram-cli -k tg-server.pub'

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
